name: Habits
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: US/Central
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          extras_css: |
            svg {
              color: white;
              font-size: 22px;
            }
            h1 {
              font-size: 24px;
              font-weight: bold;
            }
            h2 {
              font-size: 24px;
            }
            h3 {
              font-size: 24px;
            }
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
