name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: US/Central
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          extras_css: |
            svg {
              color: white;
              font-size: 16;
            }
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_people: yes
          plugin_people_types: followers, contributors
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
